version: "3.3"
services:
  csvtocsvw:
    image: "ghcr.io/mat-o-lab/csvtocsvw:latest"
    container_name: csvtocsvw
    environment:
      APP_MODE: "production"
      PORT: 8000
      #ADMIN_MAIL: ${ADMIN_MAIL}
    ports:
      - 8000:8000
    restart: always
    # networks:
    #   - ckannet
    entrypoint: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1","--proxy-headers"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info"]
      interval: 60s
      timeout: 10s
      retries: 20
